const Menu = [
    {
        id: 1,
        image: "Images/maggi.jpg",
        name: "maggi",
        category: "breakfast",
        price: "20$",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae mollitia officiis minima laudantium sint neque ducimus nulla ratione deleniti similique",
    },
    {
        id: 2,
        image: "Images/allupakoida.jpg",
        name: "allu pakoda",
        category: "evening",
        price: "30$",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae mollitia officiis minima laudantium sint neque ducimus nulla ratione deleniti similique",
    },
    {
        id: 3,
        image: "Images/corn.jpg",
        name: "corn",
        category: "breakfast",
        price: "40$",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae mollitia officiis minima laudantium sint neque ducimus nulla ratione deleniti similique",
    },
    {
        id: 4,
        image: "Images/chola.jpg",
        name: "chola",
        category: "lunch",
        price: "50$",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae mollitia officiis minima laudantium sint neque ducimus nulla ratione deleniti similique",
    },
    {
        id: 5,
        image: "Images/pizza.jpg",
        name: "pizza",
        category: "evening",
        price: "60$",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae mollitia officiis minima laudantium sint neque ducimus nulla ratione deleniti similique",
    },
    {
        id: 6,
        image: "Images/nonvegthali.jpg",
        name: "nonvegthali",
        category: "dinner",
        price: "60$",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae mollitia officiis minima laudantium sint neque ducimus nulla ratione deleniti similique",
    },
    {
        id: 7,
        image: "Images/sweet.jpg",
        name: "sweet",
        category: "dinner",
        price: "60$",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae mollitia officiis minima laudantium sint neque ducimus nulla ratione deleniti similique",
    },
    {
        id: 8,
        image: "Images/rajmarice.jpg",
        name: "Rajma rice",
        category: "lunch",
        price: "60$",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae mollitia officiis minima laudantium sint neque ducimus nulla ratione deleniti similique",
    },
    {
        id: 9,
        image: "Images/samosa.jpg",
        name: "samosa",
        category: "evening",
        price: "60$",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae mollitia officiis minima laudantium sint neque ducimus nulla ratione deleniti similique",
    }
];
export default Menu;